# Generated by Django 5.1.7 on 2025-03-31 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0003_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'is_approved': True}, on_delete=django.db.models.deletion.CASCADE, to='sparc.profile'),
        ),
    ]
