# Generated by Django 5.1.7 on 2025-03-31 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0006_sale_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='is_approved',
        ),
    ]
