# Generated by Django 5.1.7 on 2025-03-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0007_remove_sale_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
