# Generated by Django 5.1.7 on 2025-03-31 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0009_profile_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
