# Generated by Django 5.1.2 on 2025-04-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0013_developersales'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cancelled_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('developer', models.CharField(max_length=255)),
            ],
        ),
    ]
