# Generated by Django 5.1.2 on 2025-04-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0014_salesdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='active_sales',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='cancelled_sales',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
