# Generated by Django 5.1.2 on 2025-04-03 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0015_alter_salesdata_active_sales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
            preserve_default=False,
        ),
    ]
