# Generated by Django 5.1.2 on 2025-04-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparc', '0016_salesdata_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeveloperSales',
        ),
    ]
